version: '3.8'
services:
  postgres-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: clientesdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  mysql-db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: cuentasdb
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  postgres-data:
  mysql-data: